export type SupportedLocale = 'pl' | 'uk' | 'en' | 'ru';
export type TranslationKey =
  | 'foundation.title'
  | 'foundation.description'
  | 'auth.brand' | 'auth.loginTitle' | 'auth.signupTitle' | 'auth.email' | 'auth.password' | 'auth.confirmPassword' | 'auth.login' | 'auth.signup' | 'auth.logout' | 'auth.goToLogin' | 'auth.goToSignup' | 'auth.loading' | 'auth.required' | 'auth.invalidEmail' | 'auth.passwordMismatch' | 'auth.confirmEmail' | 'auth.signedUp' | 'auth.error.generic' | 'auth.error.invalidCredentials' | 'auth.error.accountExists' | 'auth.error.rateLimit' | 'auth.error.network' | 'auth.error.weakPassword'
  | 'profile.nickname.title' | 'profile.nickname.description' | 'profile.nickname.label' | 'profile.nickname.save' | 'profile.nickname.saving' | 'profile.nickname.error.required' | 'profile.nickname.error.tooShort' | 'profile.nickname.error.tooLong' | 'profile.nickname.error.invalidCharacters' | 'profile.nickname.error.conflict' | 'profile.nickname.error.network' | 'profile.nickname.error.forbidden' | 'profile.nickname.error.unknown'
  | 'navigation.loading' | 'navigation.profileError.title' | 'navigation.profileError.description' | 'navigation.blocked.title' | 'navigation.blocked.description' | 'navigation.retry' | 'navigation.retrying' | 'navigation.tab.dashboard' | 'navigation.tab.work' | 'navigation.tab.more' | 'navigation.more.title' | 'navigation.more.description' | 'navigation.more.statistics' | 'navigation.backToWork' | 'app.placeholder.title' | 'app.placeholder.nickname'
  | 'work.loading' | 'work.empty.title' | 'work.empty.description' | 'work.list.title' | 'work.shift.hours' | 'work.shift.km' | 'work.error.title' | 'work.error.description' | 'work.blocked.title' | 'work.blocked.description' | 'work.retry'
  | 'work.create.action' | 'work.create.title' | 'work.create.date' | 'work.create.km' | 'work.create.hours' | 'work.create.otherName' | 'work.create.submit' | 'work.create.submitting' | 'work.create.cancel' | 'work.create.validation' | 'work.create.validation.date' | 'work.create.validation.platform' | 'work.create.validation.number' | 'work.create.validation.nonNegative' | 'work.create.validation.ordersInteger' | 'work.create.validation.otherName' | 'work.create.duplicate' | 'work.create.recoverable' | 'work.create.reconciliation' | 'work.create.reconcile' | 'work.create.blocked' | 'work.create.success'
  | 'work.form.general' | 'work.form.platforms'
  | 'work.date.cancel' | 'work.date.confirm' | 'work.date.invalid'
  | 'work.platform.uber' | 'work.platform.wolt' | 'work.platform.bolt' | 'work.platform.glovo' | 'work.platform.stuart' | 'work.platform.other' | 'work.metric.income' | 'work.metric.orders' | 'work.metric.appTips' | 'work.metric.cashTips' | 'work.metric.bonuses'
  | 'work.edit.action' | 'work.edit.title' | 'work.edit.loading' | 'work.edit.save' | 'work.edit.saving' | 'work.edit.cancel' | 'work.edit.validation' | 'work.edit.duplicate' | 'work.edit.recoverable' | 'work.edit.blocked' | 'work.edit.notFound' | 'work.edit.reconciliation' | 'work.edit.reconcile'
  | 'work.delete.action' | 'work.delete.title' | 'work.delete.body' | 'work.delete.confirm' | 'work.delete.cancel' | 'work.delete.deleting' | 'work.delete.recoverable' | 'work.delete.blocked' | 'work.delete.reconciliation' | 'work.delete.reconcile'
  | 'dashboard.title' | 'dashboard.totalIncome' | 'dashboard.totalHours' | 'dashboard.totalOrders' | 'dashboard.totalKilometers' | 'dashboard.totalShifts' | 'dashboard.incomePerHour' | 'dashboard.incomePerOrder' | 'dashboard.incomePerKilometer' | 'dashboard.loading' | 'dashboard.empty.title' | 'dashboard.empty.description' | 'dashboard.error.title' | 'dashboard.error.description' | 'dashboard.retry' | 'dashboard.period.today' | 'dashboard.period.week' | 'dashboard.period.month' | 'dashboard.period.allTime' | 'dashboard.periodEmpty.title' | 'dashboard.periodEmpty.description'
  | 'statistics.title' | 'statistics.period.label' | 'statistics.period.today' | 'statistics.period.week' | 'statistics.period.month' | 'statistics.period.allTime' | 'statistics.totalBrutto' | 'statistics.baseIncome' | 'statistics.appTips' | 'statistics.cashTips' | 'statistics.bonuses' | 'statistics.orders' | 'statistics.workedTime' | 'statistics.distance' | 'statistics.shiftCount' | 'statistics.platformBreakdown' | 'statistics.platform.brutto' | 'statistics.platform.orders' | 'statistics.loading' | 'statistics.empty.title' | 'statistics.empty.description' | 'statistics.periodEmpty.title' | 'statistics.periodEmpty.description' | 'statistics.error.title' | 'statistics.error.description' | 'statistics.blocked.title' | 'statistics.blocked.description' | 'statistics.retry';

type TranslationDictionary = Record<TranslationKey, string>;

export const supportedLocales: readonly SupportedLocale[] = ['pl', 'uk', 'en', 'ru'];
export const defaultLocale: SupportedLocale = 'pl';

const navigationTranslations = {
  pl: {
    'navigation.tab.dashboard': 'Pulpit',
    'navigation.tab.work': 'Zmiany',
    'navigation.tab.more': 'Więcej',
    'navigation.more.title': 'Więcej',
    'navigation.more.description': 'Dodatkowe sekcje będą dostępne w kolejnych etapach.',
    'navigation.more.statistics': 'Statystyki',
    'navigation.backToWork': 'Wróć do zmian',
  },
  uk: {
    'navigation.tab.dashboard': 'Панель',
    'navigation.tab.work': 'Зміни',
    'navigation.tab.more': 'Більше',
    'navigation.more.title': 'Більше',
    'navigation.more.description': 'Додаткові розділи з’являться на наступних етапах.',
    'navigation.more.statistics': 'Статистика',
    'navigation.backToWork': 'Повернутися до змін',
  },
  en: {
    'navigation.tab.dashboard': 'Dashboard',
    'navigation.tab.work': 'Work',
    'navigation.tab.more': 'More',
    'navigation.more.title': 'More',
    'navigation.more.description': 'Additional sections will be available in later stages.',
    'navigation.more.statistics': 'Statistics',
    'navigation.backToWork': 'Back to work shifts',
  },
  ru: {
    'navigation.tab.dashboard': 'Панель',
    'navigation.tab.work': 'Смены',
    'navigation.tab.more': 'Больше',
    'navigation.more.title': 'Больше',
    'navigation.more.description': 'Дополнительные разделы появятся на следующих этапах.',
    'navigation.more.statistics': 'Статистика',
    'navigation.backToWork': 'Вернуться к сменам',
  },
} as const;

const workShiftCreateValidationTranslations = {
  pl: {
    'work.create.validation.date': 'Wprowadź prawidłową datę.',
    'work.create.validation.platform': 'Wybierz co najmniej jedną platformę.',
    'work.create.validation.number': 'Wprowadź prawidłowe wartości liczbowe.',
    'work.create.validation.nonNegative': 'Wartości liczbowe nie mogą być ujemne.',
    'work.create.validation.ordersInteger': 'Liczba zamówień musi być liczbą całkowitą.',
    'work.create.validation.otherName': 'Wprowadź nazwę innej platformy.',
  },
  uk: {
    'work.create.validation.date': 'Введіть коректну дату.',
    'work.create.validation.platform': 'Виберіть щонайменше одну платформу.',
    'work.create.validation.number': 'Введіть коректні числові значення.',
    'work.create.validation.nonNegative': 'Числові значення не можуть бути від’ємними.',
    'work.create.validation.ordersInteger': 'Кількість замовлень має бути цілим числом.',
    'work.create.validation.otherName': 'Введіть назву іншої платформи.',
  },
  en: {
    'work.create.validation.date': 'Enter a valid date.',
    'work.create.validation.platform': 'Select at least one platform.',
    'work.create.validation.number': 'Enter valid numeric values.',
    'work.create.validation.nonNegative': 'Numeric values cannot be negative.',
    'work.create.validation.ordersInteger': 'Orders must be a whole number.',
    'work.create.validation.otherName': 'Enter the Other platform name.',
  },
  ru: {
    'work.create.validation.date': 'Введите корректную дату.',
    'work.create.validation.platform': 'Выберите хотя бы одну платформу.',
    'work.create.validation.number': 'Введите корректные числовые значения.',
    'work.create.validation.nonNegative': 'Числовые значения не могут быть отрицательными.',
    'work.create.validation.ordersInteger': 'Количество заказов должно быть целым числом.',
    'work.create.validation.otherName': 'Введите название другой платформы.',
  },
} as const;

const workShiftDateTranslations = {
  pl: { 'work.date.cancel': 'Anuluj', 'work.date.confirm': 'Gotowe', 'work.date.invalid': 'Nieprawidłowa data' },
  uk: { 'work.date.cancel': 'Скасувати', 'work.date.confirm': 'Готово', 'work.date.invalid': 'Некоректна дата' },
  en: { 'work.date.cancel': 'Cancel', 'work.date.confirm': 'Done', 'work.date.invalid': 'Invalid date' },
  ru: { 'work.date.cancel': 'Отмена', 'work.date.confirm': 'Готово', 'work.date.invalid': 'Некорректная дата' },
} as const;

export const translations = {
  pl: {
    ...navigationTranslations.pl,
    ...workShiftCreateValidationTranslations.pl,
    ...workShiftDateTranslations.pl,
    'foundation.title': 'CourierDash Mobile',
    'foundation.description': 'Podstawa motywu i lokalizacji jest gotowa.',
    'auth.brand': 'CourierDash', 'auth.loginTitle': 'Zaloguj się', 'auth.signupTitle': 'Utwórz konto', 'auth.email': 'Email', 'auth.password': 'Hasło', 'auth.confirmPassword': 'Potwierdź hasło', 'auth.login': 'Zaloguj się', 'auth.signup': 'Zarejestruj się', 'auth.logout': 'Wyloguj się', 'auth.goToLogin': 'Masz konto? Zaloguj się', 'auth.goToSignup': 'Nie masz konta? Zarejestruj się', 'auth.loading': 'Ładowanie…', 'auth.required': 'To pole jest wymagane.', 'auth.invalidEmail': 'Wprowadź prawidłowy email.', 'auth.passwordMismatch': 'Hasła nie są takie same.', 'auth.confirmEmail': 'Sprawdź email, aby dokończyć rejestrację.', 'auth.signedUp': 'Rejestracja zakończona.', 'auth.error.generic': 'Nie udało się wykonać operacji. Spróbuj ponownie.', 'auth.error.invalidCredentials': 'Nieprawidłowy email lub hasło.', 'auth.error.accountExists': 'Konto już istnieje.', 'auth.error.rateLimit': 'Zbyt wiele prób. Spróbuj później.', 'auth.error.network': 'Sieć jest niedostępna. Spróbuj ponownie.', 'auth.error.weakPassword': 'Hasło nie spełnia wymagań.',
    'profile.nickname.title': 'Wybierz nazwę użytkownika', 'profile.nickname.description': 'Pomoże ona dokończyć konfigurację profilu.', 'profile.nickname.label': 'Nazwa użytkownika', 'profile.nickname.save': 'Zapisz', 'profile.nickname.saving': 'Zapisywanie…', 'profile.nickname.error.required': 'Wpisz nazwę użytkownika.', 'profile.nickname.error.tooShort': 'Nazwa musi mieć co najmniej 3 znaki.', 'profile.nickname.error.tooLong': 'Nazwa może mieć maksymalnie 15 znaków.', 'profile.nickname.error.invalidCharacters': 'Użyj tylko liter ASCII, cyfr lub podkreślenia.', 'profile.nickname.error.conflict': 'Ta nazwa użytkownika jest już zajęta.', 'profile.nickname.error.network': 'Sieć jest niedostępna. Spróbuj ponownie.', 'profile.nickname.error.forbidden': 'Nie masz uprawnień do zapisania nazwy.', 'profile.nickname.error.unknown': 'Nie udało się zapisać nazwy. Spróbuj ponownie.',
    'navigation.loading': 'Ładowanie…', 'navigation.profileError.title': 'Nie udało się załadować profilu', 'navigation.profileError.description': 'Spróbuj ponownie.', 'navigation.blocked.title': 'Profil jest tymczasowo niedostępny', 'navigation.blocked.description': 'Spróbuj ponownie później.', 'navigation.retry': 'Spróbuj ponownie', 'navigation.retrying': 'Ponawianie…', 'app.placeholder.title': 'Aplikacja kuriera', 'app.placeholder.nickname': 'Witaj.',
    'work.loading': 'Ładowanie zmian…', 'work.empty.title': 'Brak zmian', 'work.empty.description': 'Nie ma jeszcze zapisanych zmian.', 'work.list.title': 'Zmiany', 'work.shift.hours': 'Godziny', 'work.shift.km': 'Kilometry', 'work.error.title': 'Nie udało się załadować zmian', 'work.error.description': 'Spróbuj ponownie.', 'work.blocked.title': 'Zmiany są tymczasowo niedostępne', 'work.blocked.description': 'Spróbuj ponownie później.', 'work.retry': 'Spróbuj ponownie',
    'work.create.action': 'Dodaj zmianę', 'work.create.title': 'Nowa zmiana', 'work.create.date': 'Data', 'work.create.km': 'Kilometry', 'work.create.hours': 'Godziny', 'work.create.otherName': 'Nazwa platformy', 'work.create.submit': 'Zapisz zmianę', 'work.create.submitting': 'Zapisywanie…', 'work.create.cancel': 'Anuluj', 'work.create.validation': 'Sprawdź dane zmiany.', 'work.create.duplicate': 'Zmiana dla tej daty już istnieje.', 'work.create.recoverable': 'Nie udało się zapisać zmiany. Odśwież listę przed ponowną próbą.', 'work.create.reconciliation': 'Zmiana mogła zostać zapisana. Odśwież listę przed ponowną próbą.', 'work.create.reconcile': 'Odśwież listę zmian', 'work.create.blocked': 'Nie można zapisać zmiany.', 'work.create.success': 'Zmiana została zapisana.', 'work.form.general': 'Ogólne', 'work.form.platforms': 'Platformy', 'work.platform.uber': 'Uber', 'work.platform.wolt': 'Wolt', 'work.platform.bolt': 'Bolt', 'work.platform.glovo': 'Glovo', 'work.platform.stuart': 'Stuart', 'work.platform.other': 'Inna platforma', 'work.metric.income': 'Przychód', 'work.metric.orders': 'Zamówienia', 'work.metric.appTips': 'Napiwki w aplikacji', 'work.metric.cashTips': 'Napiwki gotówkowe', 'work.metric.bonuses': 'Bonusy', 'work.edit.action':'Edytuj','work.edit.title':'Edytuj zmianę','work.edit.loading':'Ładowanie zmiany…','work.edit.save':'Zapisz zmiany','work.edit.saving':'Zapisywanie…','work.edit.cancel':'Anuluj','work.edit.validation':'Sprawdź dane zmiany.','work.edit.duplicate':'Zmiana dla tej daty już istnieje.','work.edit.recoverable':'Nie udało się zaktualizować zmiany.','work.edit.blocked':'Nie można zaktualizować zmiany.','work.edit.notFound':'Zmiana nie jest dostępna.','work.edit.reconciliation':'Zmiana mogła zostać zaktualizowana. Odśwież listę.','work.edit.reconcile':'Odśwież listę zmian',
    'work.delete.action':'Usuń zmianę','work.delete.title':'Usunąć zmianę?','work.delete.body':'Ta czynność trwale usuwa wybraną zmianę.','work.delete.confirm':'Usuń','work.delete.cancel':'Anuluj','work.delete.deleting':'Usuwanie…','work.delete.recoverable':'Nie udało się usunąć zmiany. Odśwież listę i spróbuj ponownie.','work.delete.blocked':'Nie można usunąć zmiany. Odśwież listę i spróbuj ponownie.','work.delete.reconciliation':'Zmiana mogła zostać usunięta, ale lista nie została odświeżona.','work.delete.reconcile':'Odśwież listę zmian',
    'dashboard.title': 'Pulpit', 'dashboard.totalIncome': 'Łączny przychód', 'dashboard.totalHours': 'Łączne godziny', 'dashboard.totalOrders': 'Łączne zamówienia', 'dashboard.totalKilometers': 'Łączne kilometry', 'dashboard.totalShifts': 'Łączne zmiany', 'dashboard.incomePerHour': 'Przychód na godzinę', 'dashboard.incomePerOrder': 'Przychód na zamówienie', 'dashboard.incomePerKilometer': 'Przychód na kilometr', 'dashboard.loading': 'Ładowanie pulpitu…', 'dashboard.empty.title': 'Brak zmian', 'dashboard.empty.description': 'Dodaj pierwszą zmianę, aby zobaczyć metryki pulpitu.', 'dashboard.error.title': 'Pulpit jest tymczasowo niedostępny', 'dashboard.error.description': 'Spróbuj ponownie.', 'dashboard.retry': 'Spróbuj ponownie', 'dashboard.period.today': 'Dzisiaj', 'dashboard.period.week': 'Ten tydzień', 'dashboard.period.month': 'Ten miesiąc', 'dashboard.period.allTime': 'Cały czas', 'dashboard.periodEmpty.title': 'Brak zmian w tym okresie', 'dashboard.periodEmpty.description': 'Wybierz inny okres, aby zobaczyć metryki.',
    'statistics.title': 'Statystyki', 'statistics.period.label': 'Okres', 'statistics.period.today': 'Dzisiaj', 'statistics.period.week': 'Ten tydzień', 'statistics.period.month': 'Ten miesiąc', 'statistics.period.allTime': 'Cały czas', 'statistics.totalBrutto': 'Łączne brutto', 'statistics.baseIncome': 'Przychód podstawowy', 'statistics.appTips': 'Napiwki w aplikacji', 'statistics.cashTips': 'Napiwki gotówkowe', 'statistics.bonuses': 'Bonusy', 'statistics.orders': 'Zamówienia', 'statistics.workedTime': 'Czas pracy', 'statistics.distance': 'Dystans', 'statistics.shiftCount': 'Liczba zmian', 'statistics.platformBreakdown': 'Według platformy', 'statistics.platform.brutto': 'Brutto', 'statistics.platform.orders': 'Zamówienia', 'statistics.loading': 'Ładowanie statystyk…', 'statistics.empty.title': 'Brak zmian', 'statistics.empty.description': 'Dodaj pierwszą zmianę, aby zobaczyć statystyki.', 'statistics.periodEmpty.title': 'Brak zmian w tym okresie', 'statistics.periodEmpty.description': 'Wybierz inny okres, aby zobaczyć statystyki.', 'statistics.error.title': 'Statystyki są tymczasowo niedostępne', 'statistics.error.description': 'Spróbuj ponownie.', 'statistics.blocked.title': 'Statystyki są tymczasowo niedostępne', 'statistics.blocked.description': 'Spróbuj ponownie później.', 'statistics.retry': 'Spróbuj ponownie',
  },
  uk: {
    ...navigationTranslations.uk,
    ...workShiftCreateValidationTranslations.uk,
    ...workShiftDateTranslations.uk,
    'foundation.title': 'CourierDash Mobile',
    'foundation.description': 'Основу теми та локалізації підготовлено.',
    'auth.brand': 'CourierDash', 'auth.loginTitle': 'Вхід', 'auth.signupTitle': 'Створити акаунт', 'auth.email': 'Електронна пошта', 'auth.password': 'Пароль', 'auth.confirmPassword': 'Підтвердьте пароль', 'auth.login': 'Увійти', 'auth.signup': 'Зареєструватися', 'auth.logout': 'Вийти з акаунта', 'auth.goToLogin': 'Вже маєте акаунт? Увійдіть', 'auth.goToSignup': 'Немає акаунта? Зареєструйтеся', 'auth.loading': 'Завантаження…', 'auth.required': 'Поле обов’язкове.', 'auth.invalidEmail': 'Введіть коректну пошту.', 'auth.passwordMismatch': 'Паролі не збігаються.', 'auth.confirmEmail': 'Перевірте пошту, щоб завершити реєстрацію.', 'auth.signedUp': 'Реєстрацію завершено.', 'auth.error.generic': 'Не вдалося виконати операцію. Спробуйте ще раз.', 'auth.error.invalidCredentials': 'Неправильна пошта або пароль.', 'auth.error.accountExists': 'Акаунт уже існує.', 'auth.error.rateLimit': 'Забагато спроб. Спробуйте пізніше.', 'auth.error.network': 'Мережа недоступна. Спробуйте ще раз.', 'auth.error.weakPassword': 'Пароль не відповідає вимогам.',
    'profile.nickname.title': 'Оберіть нікнейм', 'profile.nickname.description': 'Він буде використаний у вашому профілі.', 'profile.nickname.label': 'Нікнейм', 'profile.nickname.save': 'Зберегти', 'profile.nickname.saving': 'Збереження…', 'profile.nickname.error.required': 'Введіть нікнейм.', 'profile.nickname.error.tooShort': 'Нікнейм має містити щонайменше 3 символи.', 'profile.nickname.error.tooLong': 'Нікнейм може містити не більше 15 символів.', 'profile.nickname.error.invalidCharacters': 'Використовуйте лише ASCII-літери, цифри або підкреслення.', 'profile.nickname.error.conflict': 'Цей нікнейм уже зайнятий.', 'profile.nickname.error.network': 'Мережа недоступна. Спробуйте ще раз.', 'profile.nickname.error.forbidden': 'Немає дозволу зберегти нікнейм.', 'profile.nickname.error.unknown': 'Не вдалося зберегти нікнейм. Спробуйте ще раз.',
    'navigation.loading': 'Завантаження…', 'navigation.profileError.title': 'Не вдалося завантажити профіль', 'navigation.profileError.description': 'Спробуйте ще раз.', 'navigation.blocked.title': 'Профіль тимчасово недоступний', 'navigation.blocked.description': 'Спробуйте пізніше.', 'navigation.retry': 'Спробувати ще раз', 'navigation.retrying': 'Повторна спроба…', 'app.placeholder.title': 'Застосунок кур’єра', 'app.placeholder.nickname': 'Вітаємо.',
    'work.loading': 'Завантаження змін…', 'work.empty.title': 'Змін немає', 'work.empty.description': 'Ще немає збережених змін.', 'work.list.title': 'Зміни', 'work.shift.hours': 'Години', 'work.shift.km': 'Кілометри', 'work.error.title': 'Не вдалося завантажити зміни', 'work.error.description': 'Спробуйте ще раз.', 'work.blocked.title': 'Зміни тимчасово недоступні', 'work.blocked.description': 'Спробуйте пізніше.', 'work.retry': 'Спробувати ще раз',
    'work.create.action': 'Додати зміну', 'work.create.title': 'Нова зміна', 'work.create.date': 'Дата', 'work.create.km': 'Кілометри', 'work.create.hours': 'Години', 'work.create.otherName': 'Назва платформи', 'work.create.submit': 'Зберегти зміну', 'work.create.submitting': 'Збереження…', 'work.create.cancel': 'Скасувати', 'work.create.validation': 'Перевірте дані зміни.', 'work.create.duplicate': 'Зміна на цю дату вже існує.', 'work.create.recoverable': 'Не вдалося зберегти зміну. Оновіть список перед повторною спробою.', 'work.create.reconciliation': 'Зміна могла бути збережена. Оновіть список перед повторною спробою.', 'work.create.reconcile': 'Оновити список змін', 'work.create.blocked': 'Не вдалося зберегти зміну.', 'work.create.success': 'Зміну збережено.', 'work.form.general': 'Загальне', 'work.form.platforms': 'Платформи', 'work.platform.uber': 'Uber', 'work.platform.wolt': 'Wolt', 'work.platform.bolt': 'Bolt', 'work.platform.glovo': 'Glovo', 'work.platform.stuart': 'Stuart', 'work.platform.other': 'Інша платформа', 'work.metric.income': 'Дохід', 'work.metric.orders': 'Замовлення', 'work.metric.appTips': 'Чайові в застосунку', 'work.metric.cashTips': 'Готівкові чайові', 'work.metric.bonuses': 'Бонуси', 'work.edit.action':'Редагувати','work.edit.title':'Редагування зміни','work.edit.loading':'Завантаження зміни…','work.edit.save':'Зберегти зміни','work.edit.saving':'Збереження…','work.edit.cancel':'Скасувати','work.edit.validation':'Перевірте дані зміни.','work.edit.duplicate':'Зміна на цю дату вже існує.','work.edit.recoverable':'Не вдалося оновити зміну.','work.edit.blocked':'Не вдалося оновити зміну.','work.edit.notFound':'Зміна недоступна.','work.edit.reconciliation':'Зміна могла бути оновлена. Оновіть список.','work.edit.reconcile':'Оновити список змін',
    'work.delete.action':'Видалити зміну','work.delete.title':'Видалити зміну?','work.delete.body':'Ця дія назавжди видаляє вибрану зміну.','work.delete.confirm':'Видалити','work.delete.cancel':'Скасувати','work.delete.deleting':'Видалення…','work.delete.recoverable':'Не вдалося видалити зміну. Оновіть список і спробуйте ще раз.','work.delete.blocked':'Не вдалося видалити зміну. Оновіть список і спробуйте ще раз.','work.delete.reconciliation':'Зміну могло бути видалено, але список не оновився.','work.delete.reconcile':'Оновити список змін',
    'dashboard.title': 'Панель', 'dashboard.totalIncome': 'Загальний дохід', 'dashboard.totalHours': 'Загальні години', 'dashboard.totalOrders': 'Загальні замовлення', 'dashboard.totalKilometers': 'Загальні кілометри', 'dashboard.totalShifts': 'Загальна кількість змін', 'dashboard.incomePerHour': 'Дохід за годину', 'dashboard.incomePerOrder': 'Дохід за замовлення', 'dashboard.incomePerKilometer': 'Дохід за кілометр', 'dashboard.loading': 'Завантаження панелі…', 'dashboard.empty.title': 'Немає змін', 'dashboard.empty.description': 'Додайте першу зміну, щоб побачити показники панелі.', 'dashboard.error.title': 'Панель тимчасово недоступна', 'dashboard.error.description': 'Спробуйте ще раз.', 'dashboard.retry': 'Спробувати ще раз', 'dashboard.period.today': 'Сьогодні', 'dashboard.period.week': 'Цей тиждень', 'dashboard.period.month': 'Цей місяць', 'dashboard.period.allTime': 'За весь час', 'dashboard.periodEmpty.title': 'У цьому періоді немає змін', 'dashboard.periodEmpty.description': 'Виберіть інший період, щоб побачити показники.',
    'statistics.title': 'Статистика', 'statistics.period.label': 'Період', 'statistics.period.today': 'Сьогодні', 'statistics.period.week': 'Цей тиждень', 'statistics.period.month': 'Цей місяць', 'statistics.period.allTime': 'За весь час', 'statistics.totalBrutto': 'Загальна сума брутто', 'statistics.baseIncome': 'Базовий дохід', 'statistics.appTips': 'Чайові в застосунку', 'statistics.cashTips': 'Готівкові чайові', 'statistics.bonuses': 'Бонуси', 'statistics.orders': 'Замовлення', 'statistics.workedTime': 'Робочий час', 'statistics.distance': 'Відстань', 'statistics.shiftCount': 'Кількість змін', 'statistics.platformBreakdown': 'За платформами', 'statistics.platform.brutto': 'Брутто', 'statistics.platform.orders': 'Замовлення', 'statistics.loading': 'Завантаження статистики…', 'statistics.empty.title': 'Немає змін', 'statistics.empty.description': 'Додайте першу зміну, щоб побачити статистику.', 'statistics.periodEmpty.title': 'У цьому періоді немає змін', 'statistics.periodEmpty.description': 'Виберіть інший період, щоб побачити статистику.', 'statistics.error.title': 'Статистика тимчасово недоступна', 'statistics.error.description': 'Спробуйте ще раз.', 'statistics.blocked.title': 'Статистика тимчасово недоступна', 'statistics.blocked.description': 'Спробуйте пізніше.', 'statistics.retry': 'Спробувати ще раз',
  },
  en: {
    ...navigationTranslations.en,
    ...workShiftCreateValidationTranslations.en,
    ...workShiftDateTranslations.en,
    'foundation.title': 'CourierDash Mobile',
    'foundation.description': 'Theme and localization foundation is ready.',
    'auth.brand': 'CourierDash', 'auth.loginTitle': 'Sign in', 'auth.signupTitle': 'Create account', 'auth.email': 'Email', 'auth.password': 'Password', 'auth.confirmPassword': 'Confirm password', 'auth.login': 'Sign in', 'auth.signup': 'Sign up', 'auth.logout': 'Log out', 'auth.goToLogin': 'Have an account? Sign in', 'auth.goToSignup': 'Need an account? Sign up', 'auth.loading': 'Loading…', 'auth.required': 'This field is required.', 'auth.invalidEmail': 'Enter a valid email.', 'auth.passwordMismatch': 'Passwords do not match.', 'auth.confirmEmail': 'Check your email to complete registration.', 'auth.signedUp': 'Registration completed.', 'auth.error.generic': 'Unable to complete the operation. Try again.', 'auth.error.invalidCredentials': 'Invalid email or password.', 'auth.error.accountExists': 'An account already exists.', 'auth.error.rateLimit': 'Too many attempts. Try later.', 'auth.error.network': 'Network unavailable. Try again.', 'auth.error.weakPassword': 'Password does not meet requirements.',
    'profile.nickname.title': 'Choose a nickname', 'profile.nickname.description': 'It will be used in your profile.', 'profile.nickname.label': 'Nickname', 'profile.nickname.save': 'Save nickname', 'profile.nickname.saving': 'Saving…', 'profile.nickname.error.required': 'Enter a nickname.', 'profile.nickname.error.tooShort': 'Nickname must contain at least 3 characters.', 'profile.nickname.error.tooLong': 'Nickname can contain at most 15 characters.', 'profile.nickname.error.invalidCharacters': 'Use only ASCII letters, numbers, or underscores.', 'profile.nickname.error.conflict': 'This nickname is already taken.', 'profile.nickname.error.network': 'Network unavailable. Try again.', 'profile.nickname.error.forbidden': 'You are not allowed to save this nickname.', 'profile.nickname.error.unknown': 'Unable to save nickname. Try again.',
    'navigation.loading': 'Loading…', 'navigation.profileError.title': 'Unable to load profile', 'navigation.profileError.description': 'Try again.', 'navigation.blocked.title': 'Profile is temporarily unavailable', 'navigation.blocked.description': 'Try again later.', 'navigation.retry': 'Retry', 'navigation.retrying': 'Retrying…', 'app.placeholder.title': 'Courier application', 'app.placeholder.nickname': 'Welcome.',
    'work.loading': 'Loading shifts…', 'work.empty.title': 'No shifts yet', 'work.empty.description': 'There are no saved shifts yet.', 'work.list.title': 'Shifts', 'work.shift.hours': 'Hours', 'work.shift.km': 'Kilometres', 'work.error.title': 'Unable to load shifts', 'work.error.description': 'Try again.', 'work.blocked.title': 'Shifts are temporarily unavailable', 'work.blocked.description': 'Try again later.', 'work.retry': 'Retry',
    'work.create.action': 'Add shift', 'work.create.title': 'New shift', 'work.create.date': 'Date', 'work.create.km': 'Kilometres', 'work.create.hours': 'Hours', 'work.create.otherName': 'Platform name', 'work.create.submit': 'Save shift', 'work.create.submitting': 'Saving…', 'work.create.cancel': 'Cancel', 'work.create.validation': 'Check the shift details.', 'work.create.duplicate': 'A shift already exists for this date.', 'work.create.recoverable': 'Unable to save the shift. Refresh the list before trying again.', 'work.create.reconciliation': 'The shift may have been saved. Refresh the list before trying again.', 'work.create.reconcile': 'Refresh shift list', 'work.create.blocked': 'Unable to save the shift.', 'work.create.success': 'Shift saved.', 'work.form.general': 'General', 'work.form.platforms': 'Platforms', 'work.platform.uber': 'Uber', 'work.platform.wolt': 'Wolt', 'work.platform.bolt': 'Bolt', 'work.platform.glovo': 'Glovo', 'work.platform.stuart': 'Stuart', 'work.platform.other': 'Other platform', 'work.metric.income': 'Income', 'work.metric.orders': 'Orders', 'work.metric.appTips': 'App tips', 'work.metric.cashTips': 'Cash tips', 'work.metric.bonuses': 'Bonuses', 'work.edit.action':'Edit','work.edit.title':'Edit shift','work.edit.loading':'Loading shift…','work.edit.save':'Save changes','work.edit.saving':'Saving…','work.edit.cancel':'Cancel','work.edit.validation':'Check the shift details.','work.edit.duplicate':'A shift already exists for this date.','work.edit.recoverable':'Unable to update the shift.','work.edit.blocked':'Unable to update the shift.','work.edit.notFound':'Shift is unavailable.','work.edit.reconciliation':'The shift may have been updated. Refresh the list.','work.edit.reconcile':'Refresh shift list',
    'work.delete.action':'Delete shift','work.delete.title':'Delete work shift?','work.delete.body':'This action permanently removes the selected work shift.','work.delete.confirm':'Delete','work.delete.cancel':'Cancel','work.delete.deleting':'Deleting…','work.delete.recoverable':'The shift could not be deleted. Refresh the list and try again.','work.delete.blocked':'The shift could not be deleted. Refresh the list and try again.','work.delete.reconciliation':'The shift may already be deleted, but the list could not be refreshed.','work.delete.reconcile':'Refresh shift list',
    'dashboard.title': 'Dashboard', 'dashboard.totalIncome': 'Total income', 'dashboard.totalHours': 'Total hours', 'dashboard.totalOrders': 'Total orders', 'dashboard.totalKilometers': 'Total kilometers', 'dashboard.totalShifts': 'Total shifts', 'dashboard.incomePerHour': 'Income per hour', 'dashboard.incomePerOrder': 'Income per order', 'dashboard.incomePerKilometer': 'Income per kilometer', 'dashboard.loading': 'Loading dashboard…', 'dashboard.empty.title': 'No work shifts yet', 'dashboard.empty.description': 'Add your first shift to see dashboard metrics.', 'dashboard.error.title': 'Dashboard is temporarily unavailable', 'dashboard.error.description': 'Please try again.', 'dashboard.retry': 'Try again', 'dashboard.period.today': 'Today', 'dashboard.period.week': 'This week', 'dashboard.period.month': 'This month', 'dashboard.period.allTime': 'All time', 'dashboard.periodEmpty.title': 'No shifts in this period', 'dashboard.periodEmpty.description': 'Choose another period to see metrics.',
    'statistics.title': 'Statistics', 'statistics.period.label': 'Period', 'statistics.period.today': 'Today', 'statistics.period.week': 'This week', 'statistics.period.month': 'This month', 'statistics.period.allTime': 'All time', 'statistics.totalBrutto': 'Total Brutto', 'statistics.baseIncome': 'Base income', 'statistics.appTips': 'App tips', 'statistics.cashTips': 'Cash tips', 'statistics.bonuses': 'Bonuses', 'statistics.orders': 'Orders', 'statistics.workedTime': 'Worked time', 'statistics.distance': 'Distance', 'statistics.shiftCount': 'Shift count', 'statistics.platformBreakdown': 'By platform', 'statistics.platform.brutto': 'Brutto', 'statistics.platform.orders': 'Orders', 'statistics.loading': 'Loading statistics…', 'statistics.empty.title': 'No work shifts yet', 'statistics.empty.description': 'Add your first shift to see statistics.', 'statistics.periodEmpty.title': 'No shifts in this period', 'statistics.periodEmpty.description': 'Choose another period to see statistics.', 'statistics.error.title': 'Statistics are temporarily unavailable', 'statistics.error.description': 'Please try again.', 'statistics.blocked.title': 'Statistics are temporarily unavailable', 'statistics.blocked.description': 'Please try again later.', 'statistics.retry': 'Try again',
  },
  ru: {
    ...navigationTranslations.ru,
    ...workShiftCreateValidationTranslations.ru,
    ...workShiftDateTranslations.ru,
    'foundation.title': 'CourierDash Mobile',
    'foundation.description': 'Основа темы и локализации готова.',
    'auth.brand': 'CourierDash', 'auth.loginTitle': 'Вход', 'auth.signupTitle': 'Создать аккаунт', 'auth.email': 'Электронная почта', 'auth.password': 'Пароль', 'auth.confirmPassword': 'Подтвердите пароль', 'auth.login': 'Войти', 'auth.signup': 'Зарегистрироваться', 'auth.logout': 'Выйти из аккаунта', 'auth.goToLogin': 'Уже есть аккаунт? Войдите', 'auth.goToSignup': 'Нет аккаунта? Зарегистрируйтесь', 'auth.loading': 'Загрузка…', 'auth.required': 'Поле обязательно.', 'auth.invalidEmail': 'Введите корректную почту.', 'auth.passwordMismatch': 'Пароли не совпадают.', 'auth.confirmEmail': 'Проверьте почту, чтобы завершить регистрацию.', 'auth.signedUp': 'Регистрация завершена.', 'auth.error.generic': 'Не удалось выполнить операцию. Попробуйте ещё раз.', 'auth.error.invalidCredentials': 'Неверная почта или пароль.', 'auth.error.accountExists': 'Аккаунт уже существует.', 'auth.error.rateLimit': 'Слишком много попыток. Попробуйте позже.', 'auth.error.network': 'Сеть недоступна. Попробуйте ещё раз.', 'auth.error.weakPassword': 'Пароль не соответствует требованиям.',
    'profile.nickname.title': 'Выберите никнейм', 'profile.nickname.description': 'Он будет использоваться в вашем профиле.', 'profile.nickname.label': 'Никнейм', 'profile.nickname.save': 'Сохранить', 'profile.nickname.saving': 'Сохранение…', 'profile.nickname.error.required': 'Введите никнейм.', 'profile.nickname.error.tooShort': 'Никнейм должен содержать не менее 3 символов.', 'profile.nickname.error.tooLong': 'Никнейм может содержать не более 15 символов.', 'profile.nickname.error.invalidCharacters': 'Используйте только ASCII-буквы, цифры или подчёркивание.', 'profile.nickname.error.conflict': 'Этот никнейм уже занят.', 'profile.nickname.error.network': 'Сеть недоступна. Попробуйте ещё раз.', 'profile.nickname.error.forbidden': 'Нет разрешения сохранить никнейм.', 'profile.nickname.error.unknown': 'Не удалось сохранить никнейм. Попробуйте ещё раз.',
    'navigation.loading': 'Загрузка…', 'navigation.profileError.title': 'Не удалось загрузить профиль', 'navigation.profileError.description': 'Попробуйте ещё раз.', 'navigation.blocked.title': 'Профиль временно недоступен', 'navigation.blocked.description': 'Попробуйте позже.', 'navigation.retry': 'Повторить', 'navigation.retrying': 'Повтор…', 'app.placeholder.title': 'Приложение курьера', 'app.placeholder.nickname': 'Добро пожаловать.',
    'work.loading': 'Загрузка смен…', 'work.empty.title': 'Смен пока нет', 'work.empty.description': 'Сохранённых смен пока нет.', 'work.list.title': 'Смены', 'work.shift.hours': 'Часы', 'work.shift.km': 'Километры', 'work.error.title': 'Не удалось загрузить смены', 'work.error.description': 'Попробуйте ещё раз.', 'work.blocked.title': 'Смены временно недоступны', 'work.blocked.description': 'Попробуйте позже.', 'work.retry': 'Повторить',
    'work.create.action': 'Добавить смену', 'work.create.title': 'Новая смена', 'work.create.date': 'Дата', 'work.create.km': 'Километры', 'work.create.hours': 'Часы', 'work.create.otherName': 'Название платформы', 'work.create.submit': 'Сохранить смену', 'work.create.submitting': 'Сохранение…', 'work.create.cancel': 'Отмена', 'work.create.validation': 'Проверьте данные смены.', 'work.create.duplicate': 'Смена на эту дату уже существует.', 'work.create.recoverable': 'Не удалось сохранить смену. Обновите список перед повторной попыткой.', 'work.create.reconciliation': 'Смена могла быть сохранена. Обновите список перед повторной попыткой.', 'work.create.reconcile': 'Обновить список смен', 'work.create.blocked': 'Не удалось сохранить смену.', 'work.create.success': 'Смена сохранена.', 'work.form.general': 'Общее', 'work.form.platforms': 'Платформы', 'work.platform.uber': 'Uber', 'work.platform.wolt': 'Wolt', 'work.platform.bolt': 'Bolt', 'work.platform.glovo': 'Glovo', 'work.platform.stuart': 'Stuart', 'work.platform.other': 'Другая платформа', 'work.metric.income': 'Доход', 'work.metric.orders': 'Заказы', 'work.metric.appTips': 'Чаевые в приложении', 'work.metric.cashTips': 'Наличные чаевые', 'work.metric.bonuses': 'Бонусы', 'work.edit.action':'Редактировать','work.edit.title':'Редактирование смены','work.edit.loading':'Загрузка смены…','work.edit.save':'Сохранить изменения','work.edit.saving':'Сохранение…','work.edit.cancel':'Отмена','work.edit.validation':'Проверьте данные смены.','work.edit.duplicate':'Смена на эту дату уже существует.','work.edit.recoverable':'Не удалось обновить смену.','work.edit.blocked':'Не удалось обновить смену.','work.edit.notFound':'Смена недоступна.','work.edit.reconciliation':'Смена могла быть обновлена.','work.edit.reconcile':'Обновить список смен',
    'work.delete.action':'Удалить смену','work.delete.title':'Удалить смену?','work.delete.body':'Это действие навсегда удалит выбранную смену.','work.delete.confirm':'Удалить','work.delete.cancel':'Отмена','work.delete.deleting':'Удаление…','work.delete.recoverable':'Не удалось удалить смену. Обновите список и попробуйте снова.','work.delete.blocked':'Не удалось удалить смену. Обновите список и попробуйте снова.','work.delete.reconciliation':'Смена могла быть удалена, но список не обновился.','work.delete.reconcile':'Обновить список смен',
    'dashboard.title': 'Панель', 'dashboard.totalIncome': 'Общий доход', 'dashboard.totalHours': 'Общие часы', 'dashboard.totalOrders': 'Общие заказы', 'dashboard.totalKilometers': 'Общие километры', 'dashboard.totalShifts': 'Всего смен', 'dashboard.incomePerHour': 'Доход за час', 'dashboard.incomePerOrder': 'Доход за заказ', 'dashboard.incomePerKilometer': 'Доход за километр', 'dashboard.loading': 'Загрузка панели…', 'dashboard.empty.title': 'Смен пока нет', 'dashboard.empty.description': 'Добавьте первую смену, чтобы увидеть показатели панели.', 'dashboard.error.title': 'Панель временно недоступна', 'dashboard.error.description': 'Попробуйте ещё раз.', 'dashboard.retry': 'Повторить', 'dashboard.period.today': 'Сегодня', 'dashboard.period.week': 'Эта неделя', 'dashboard.period.month': 'Этот месяц', 'dashboard.period.allTime': 'За всё время', 'dashboard.periodEmpty.title': 'В этом периоде нет смен', 'dashboard.periodEmpty.description': 'Выберите другой период, чтобы увидеть показатели.',
    'statistics.title': 'Статистика', 'statistics.period.label': 'Период', 'statistics.period.today': 'Сегодня', 'statistics.period.week': 'Эта неделя', 'statistics.period.month': 'Этот месяц', 'statistics.period.allTime': 'За всё время', 'statistics.totalBrutto': 'Общее брутто', 'statistics.baseIncome': 'Базовый доход', 'statistics.appTips': 'Чаевые в приложении', 'statistics.cashTips': 'Наличные чаевые', 'statistics.bonuses': 'Бонусы', 'statistics.orders': 'Заказы', 'statistics.workedTime': 'Рабочее время', 'statistics.distance': 'Расстояние', 'statistics.shiftCount': 'Количество смен', 'statistics.platformBreakdown': 'По платформам', 'statistics.platform.brutto': 'Брутто', 'statistics.platform.orders': 'Заказы', 'statistics.loading': 'Загрузка статистики…', 'statistics.empty.title': 'Смен пока нет', 'statistics.empty.description': 'Добавьте первую смену, чтобы увидеть статистику.', 'statistics.periodEmpty.title': 'В этом периоде нет смен', 'statistics.periodEmpty.description': 'Выберите другой период, чтобы увидеть статистику.', 'statistics.error.title': 'Статистика временно недоступна', 'statistics.error.description': 'Попробуйте ещё раз.', 'statistics.blocked.title': 'Статистика временно недоступна', 'statistics.blocked.description': 'Попробуйте позже.', 'statistics.retry': 'Повторить',
  },
} as const satisfies Record<SupportedLocale, TranslationDictionary>;
