import { supabase } from '@/lib/supabase/client';
import type { Database } from '@/lib/supabase/database.types';

import type { EditableOtherPlatform, EditablePlatform, WorkShiftEditable } from '../domain/workShiftEditable';

const editableSelect = 'id, date, km, hours, uber, orders_uber, tips_uber, cash_tips_uber, bonuses_uber, wolt, orders_wolt, tips_wolt, cash_tips_wolt, bonuses_wolt, bolt, orders_bolt, tips_bolt, cash_tips_bolt, bonuses_bolt, glovo, orders_glovo, tips_glovo, cash_tips_glovo, bonuses_glovo, stuart, orders_stuart, tips_stuart, cash_tips_stuart, bonuses_stuart, other_income, orders_other, tips_other, cash_tips_other, bonuses_other, other_platform_name' as const;
type DetailRow = Pick<Database['public']['Tables']['work_shifts']['Row'], 'id' | 'date' | 'km' | 'hours' | 'uber' | 'orders_uber' | 'tips_uber' | 'cash_tips_uber' | 'bonuses_uber' | 'wolt' | 'orders_wolt' | 'tips_wolt' | 'cash_tips_wolt' | 'bonuses_wolt' | 'bolt' | 'orders_bolt' | 'tips_bolt' | 'cash_tips_bolt' | 'bonuses_bolt' | 'glovo' | 'orders_glovo' | 'tips_glovo' | 'cash_tips_glovo' | 'bonuses_glovo' | 'stuart' | 'orders_stuart' | 'tips_stuart' | 'cash_tips_stuart' | 'bonuses_stuart' | 'other_income' | 'orders_other' | 'tips_other' | 'cash_tips_other' | 'bonuses_other' | 'other_platform_name'>;

export type WorkShiftDetailErrorCategory = 'not_found' | 'recoverable' | 'blocked' | 'invalid_response';
export class WorkShiftDetailError extends Error { constructor(readonly category: WorkShiftDetailErrorCategory) { super('Work shift detail failed.'); } }
function isDate(value: unknown): value is string { if (typeof value !== 'string' || !/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const [y,m,d] = value.split('-').map(Number); const date = new Date(Date.UTC(y,m-1,d)); return date.getUTCFullYear()===y && date.getUTCMonth()===m-1 && date.getUTCDate()===d; }
function validMetric(value: unknown): value is number | null { return value === null || (typeof value === 'number' && Number.isFinite(value) && value >= 0); }
function platform(income: number, orders: number | null, appTips: number | null, cashTips: number, bonuses: number | null): EditablePlatform { return { enabled: income !== 0 || orders !== null && orders !== 0 || appTips !== null && appTips !== 0 || cashTips !== 0 || bonuses !== null && bonuses !== 0, income, orders, appTips, cashTips, bonuses }; }
export function mapWorkShiftEditable(row: DetailRow): WorkShiftEditable {
  const numeric = [row.id,row.km,row.hours,row.uber,row.cash_tips_uber,row.wolt,row.cash_tips_wolt,row.bolt,row.cash_tips_bolt,row.glovo,row.cash_tips_glovo,row.stuart,row.cash_tips_stuart,row.other_income,row.cash_tips_other];
  const nullable = [row.orders_uber,row.tips_uber,row.bonuses_uber,row.orders_wolt,row.tips_wolt,row.bonuses_wolt,row.orders_bolt,row.tips_bolt,row.bonuses_bolt,row.orders_glovo,row.tips_glovo,row.bonuses_glovo,row.orders_stuart,row.tips_stuart,row.bonuses_stuart,row.orders_other,row.tips_other,row.bonuses_other];
  if (!Number.isInteger(row.id) || row.id <= 0 || !isDate(row.date) || !numeric.every((value) => typeof value === 'number' && Number.isFinite(value) && value >= 0) || !nullable.every(validMetric) || (row.other_platform_name !== null && typeof row.other_platform_name !== 'string')) throw new WorkShiftDetailError('invalid_response');
  const other = { ...platform(row.other_income,row.orders_other,row.tips_other,row.cash_tips_other,row.bonuses_other), name: row.other_platform_name } satisfies EditableOtherPlatform;
  if (other.name !== null) other.enabled = true;
  const platforms = { uber: platform(row.uber,row.orders_uber,row.tips_uber,row.cash_tips_uber,row.bonuses_uber), wolt: platform(row.wolt,row.orders_wolt,row.tips_wolt,row.cash_tips_wolt,row.bonuses_wolt), bolt: platform(row.bolt,row.orders_bolt,row.tips_bolt,row.cash_tips_bolt,row.bonuses_bolt), glovo: platform(row.glovo,row.orders_glovo,row.tips_glovo,row.cash_tips_glovo,row.bonuses_glovo), stuart: platform(row.stuart,row.orders_stuart,row.tips_stuart,row.cash_tips_stuart,row.bonuses_stuart), other };
  if (!Object.values(platforms).some((item) => item.enabled)) platforms.uber.enabled = true;
  return { id: row.id, date: row.date, km: row.km, hours: row.hours, platforms };
}
function classify(error: unknown): WorkShiftDetailErrorCategory { const value = error as { code?: string; status?: number; message?: string }; const message=value?.message?.toLowerCase() ?? ''; if(value?.code==='42501'||value?.status===401||value?.status===403||message.includes('permission')) return 'blocked'; if(message.includes('network')||message.includes('fetch')||message.includes('timeout')) return 'recoverable'; return 'recoverable'; }
export async function getOwnWorkShiftById(userId: string, shiftId: number): Promise<WorkShiftEditable> { if (!Number.isInteger(shiftId)||shiftId<=0) throw new WorkShiftDetailError('not_found'); const { data,error }=await supabase.from('work_shifts').select(editableSelect).eq('id',shiftId).eq('user_id',userId).maybeSingle(); if(error) throw new WorkShiftDetailError(classify(error)); if(data===null) throw new WorkShiftDetailError('not_found'); return mapWorkShiftEditable(data as DetailRow); }
