import { ScrollView, View } from 'react-native';
import { useEffect, useState } from 'react';
import { AppButton } from '@/components/ui/AppButton';
import { AppInput } from '@/components/ui/AppInput';
import { AppText } from '@/components/ui/AppText';
import { Screen } from '@/components/ui/Screen';
import { useLocalization } from '@/i18n/LocalizationProvider';
import { useTheme } from '@/theme/ThemeProvider';
import { editableWorkPlatformKeys, type EditableWorkPlatformKey } from '../domain/workShiftEditable';
import type { WorkShiftEditInput } from '../domain/workShiftEdit';
import { useWorkShiftEdit } from '../hooks/useWorkShiftEdit';
import { WorkShiftDateField } from './WorkShiftDateField';

type Props={onCancel:()=>void}; const metrics=['income','orders','appTips','cashTips','bonuses'] as const;
const parse=(value:string)=>value.trim()===''?Number.NaN:Number(value);
function formatEditNumericValue(value: number | null): string {
  return value === null || Number.isNaN(value) ? '' : String(value);
}
export function WorkShiftEditForm({onCancel}:Props){const edit=useWorkShiftEdit();const {t}=useLocalization();const {spacing}=useTheme();const [input,setInput]=useState<WorkShiftEditInput|null>(null);const pending=edit.status==='submitting';const reconciliation=edit.status==='reconciliation_required';useEffect(()=>{if(edit.status==='success')onCancel();},[edit.status,onCancel]);if(edit.status==='loading')return <Screen><AppText>{t('work.edit.loading')}</AppText></Screen>;if(edit.status==='recoverable_error'||edit.status==='blocked'||edit.status==='not_found')return <Screen><View style={{padding:spacing.xl,gap:spacing.md}}><AppText accessibilityRole="alert">{t(edit.status==='blocked'?'work.edit.blocked':edit.status==='not_found'?'work.edit.notFound':'work.edit.recoverable')}</AppText><AppButton label={t('work.edit.cancel')} onPress={()=>{edit.reset();onCancel();}} /></View></Screen>;const currentInput=input??(('input' in edit)?edit.input:null);if(currentInput===null)return null;
 const update=(platform:EditableWorkPlatformKey,patch:Partial<WorkShiftEditInput['platforms'][EditableWorkPlatformKey]>)=>setInput(current=>{const base=current??currentInput;return {...base,platforms:{...base.platforms,[platform]:{...base.platforms[platform],...patch}}}}); const key=edit.status==='validation_error'?'work.edit.validation':edit.status==='duplicate_date'?'work.edit.duplicate':reconciliation?'work.edit.reconciliation':null;
 return <Screen><ScrollView contentContainerStyle={{padding:spacing.xl,gap:spacing.md}}><AppText variant="title">{t('work.edit.title')}</AppText><WorkShiftDateField label={t('work.create.date')} value={currentInput.date} onChange={date=>setInput(current=>({... (current??currentInput),date}))} testID="work-edit-date"/><AppInput label={t('work.create.km')} value={formatEditNumericValue(currentInput.km)} keyboardType="decimal-pad" onChangeText={value=>setInput(current=>({... (current??currentInput),km:parse(value)}))} testID="work-edit-km"/><AppInput label={t('work.create.hours')} value={formatEditNumericValue(currentInput.hours)} keyboardType="decimal-pad" onChangeText={value=>setInput(current=>({... (current??currentInput),hours:parse(value)}))} testID="work-edit-hours"/>{editableWorkPlatformKeys.map(platform=>{const value=currentInput.platforms[platform];return <View key={platform} style={{gap:spacing.xs}}><AppButton label={t(`work.platform.${platform}`)} onPress={()=>update(platform,{enabled:!value.enabled})} testID={`work-edit-platform-${platform}`}/>{value.enabled?<View style={{gap:spacing.xs}}>{platform==='other'?<AppInput label={t('work.create.otherName')} value={currentInput.platforms.other.name??''} onChangeText={name=>update('other',{name})} testID="work-edit-other-name"/>:null}{metrics.map(metric=><AppInput key={metric} label={t(`work.metric.${metric}`)} value={formatEditNumericValue(value[metric])} keyboardType="decimal-pad" onChangeText={text=>update(platform,{[metric]:parse(text)})} testID={`work-edit-${platform}-${metric}`}/>)}</View>:null}</View>;})}{key?<AppText accessibilityRole="alert">{t(key)}</AppText>:null}{reconciliation?<AppButton label={t('work.edit.reconcile')} onPress={()=>void edit.reconcile()} testID="work-edit-reconcile"/>:<AppButton disabled={pending} label={t(pending?'work.edit.saving':'work.edit.save')} onPress={()=>void edit.submit(currentInput)} testID="work-edit-submit"/>}<AppButton disabled={pending} label={t('work.edit.cancel')} onPress={()=>{edit.reset();onCancel();}} testID="work-edit-cancel"/></ScrollView></Screen>;
}
