import { beforeEach, describe, expect, jest, test } from '@jest/globals';

const mockMaybeSingle = jest.fn<any>(); const mockDetailUserEq = jest.fn<any>(() => ({ maybeSingle: mockMaybeSingle })); const mockDetailIdEq = jest.fn<any>(() => ({ eq: mockDetailUserEq })); const mockDetailSelect = jest.fn<any>(() => ({ eq: mockDetailIdEq }));
const mockUpdateSelect = jest.fn<any>(); const mockUpdateUserEq = jest.fn<any>(() => ({ select: mockUpdateSelect })); const mockUpdateIdEq = jest.fn<any>(() => ({ eq: mockUpdateUserEq })); const mockUpdate = jest.fn<any>(() => ({ eq: mockUpdateIdEq }));
const mockFrom = jest.fn<any>(() => ({ select: mockDetailSelect, update: mockUpdate }));
jest.mock('@/lib/supabase/client', () => ({ supabase: { from: mockFrom } }));
const { getOwnWorkShiftById, WorkShiftDetailError } = require('@/features/work/api/workShiftDetailsApi') as typeof import('@/features/work/api/workShiftDetailsApi');
const { updateOwnWorkShift, toWorkShiftUpdatePayload, WorkShiftMutationError } = require('@/features/work/api/workShiftMutationsApi') as typeof import('@/features/work/api/workShiftMutationsApi');
const { validateWorkShiftEdit } = require('@/features/work/domain/workShiftEditValidation') as typeof import('@/features/work/domain/workShiftEditValidation');
const { toWorkShiftEditInput } = require('@/features/work/domain/workShiftEdit') as typeof import('@/features/work/domain/workShiftEdit');

const row={id:1,date:'2026-07-29',km:1,hours:2,uber:3,orders_uber:null,tips_uber:null,cash_tips_uber:0,bonuses_uber:null,wolt:0,orders_wolt:null,tips_wolt:null,cash_tips_wolt:0,bonuses_wolt:null,bolt:0,orders_bolt:null,tips_bolt:null,cash_tips_bolt:0,bonuses_bolt:null,glovo:0,orders_glovo:null,tips_glovo:null,cash_tips_glovo:0,bonuses_glovo:null,stuart:0,orders_stuart:0,tips_stuart:0,cash_tips_stuart:0,bonuses_stuart:0,other_income:0,orders_other:0,tips_other:0,cash_tips_other:0,bonuses_other:0,other_platform_name:null};
describe('work shift edit APIs',()=>{beforeEach(()=>{jest.clearAllMocks();mockMaybeSingle.mockResolvedValue({data:row,error:null});mockUpdateSelect.mockResolvedValue({data:[{id:1}],error:null});});test('reads exact canonical detail using table, id and owner filters',async()=>{const result=await getOwnWorkShiftById('user-a',1);expect(mockFrom).toHaveBeenCalledWith('work_shifts');expect(mockDetailSelect.mock.calls[0][0]).toContain('other_platform_name');expect(mockDetailSelect.mock.calls[0][0]).not.toContain('*');expect(mockDetailIdEq).toHaveBeenCalledWith('id',1);expect(mockDetailUserEq).toHaveBeenCalledWith('user_id','user-a');expect(result).toMatchObject({id:1,date:'2026-07-29'});});test('maps zero detail row and malformed input safely',async()=>{mockMaybeSingle.mockResolvedValueOnce({data:null,error:null});await expect(getOwnWorkShiftById('user-a',1)).rejects.toMatchObject({category:'not_found'});await expect(getOwnWorkShiftById('user-a',0)).rejects.toBeInstanceOf(WorkShiftDetailError);mockMaybeSingle.mockResolvedValueOnce({data:{...row,date:'bad'},error:null});await expect(getOwnWorkShiftById('user-a',1)).rejects.toMatchObject({category:'invalid_response'});});test('updates exact allowlisted payload with affected-row verification',async()=>{const editable=await getOwnWorkShiftById('user-a',1);const validation=validateWorkShiftEdit(toWorkShiftEditInput(editable));if(!validation.isValid)throw new Error('valid fixture');await updateOwnWorkShift('user-a',1,validation.value);expect(mockUpdate).toHaveBeenCalledWith(toWorkShiftUpdatePayload(validation.value));expect(mockUpdateIdEq).toHaveBeenCalledWith('id',1);expect(mockUpdateUserEq).toHaveBeenCalledWith('user_id','user-a');expect(mockUpdateSelect).toHaveBeenCalledWith('id');});test('treats zero or wrong affected rows as safe failure',async()=>{const editable=await getOwnWorkShiftById('user-a',1);const validation=validateWorkShiftEdit(toWorkShiftEditInput(editable));if(!validation.isValid)throw new Error('valid fixture');mockUpdateSelect.mockResolvedValueOnce({data:[],error:null});await expect(updateOwnWorkShift('user-a',1,validation.value)).rejects.toBeInstanceOf(WorkShiftMutationError);mockUpdateSelect.mockResolvedValueOnce({data:[{id:2}],error:null});await expect(updateOwnWorkShift('user-a',1,validation.value)).rejects.toBeInstanceOf(WorkShiftMutationError);});});
